### PR TITLE
CA-10 Tag based authorization

### PR DESCRIPTION
**Pull request by fvazquez-caylent**
To allow for further tightening of IAM permissions, the RDS module should allow users to set tags that will be applied to the RDS postrgre database and every resource created because of this module.

Summary of changes:

Add new variable tags.
Propagate the tags to untagged resources.
Add deprecation notice for additional_tags, update descriptions to keep consistency across modules.
Create Examples/Minimal with exampled tags.

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by souza-dan — APPROVED** [review]
LGTM

**Pull request merged**
