### PR TITLE
DEV-14965 - Removes patch version from the engine version

### PR DESCRIPTION
**Pull request by souza-dan**
Also makes `auto_minor_version_upgrade` configurable.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#auto_minor_version_upgrade

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by pkuber-tamr — APPROVED** [review]

**Review by daniosim — APPROVED** [review]
If we set `auto_minor_version_upgrade` to true, would we want to add `engine_version` to the list of fields in `ignore_changes`? Just wondering since terraform might try to recreate the rds instance if the engine version has minor version upgrades.

**Comment by souza-dan** [comment]
> If we set `auto_minor_version_upgrade` to true, would we want to add `engine_version` to the list of fields in `ignore_changes`? Just wondering since terraform might try to recreate the rds instance if the engine version has minor version upgrades.

@olivito did some experimentation here and by setting version to something without the minor version (like `12`), terraform doesn't perceive 12 vs 12.5 a difference. Although I guess we won't know for sure until something like 12.6 comes out.

https://tamr.slack.com/archives/C029912159T/p1627418570022600?thread_ts=1627413160.010800&cid=C029912159T

**Pull request merged**
