### PR TITLE
SUP-5427 Pass tags to aws_db_sunbet_group

### PR DESCRIPTION
**Pull request by along528**

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by souza-dan** [comment]
This change is covered by this PR:
https://github.com/Datatamer/terraform-aws-rds-postgres/pull/17

**Comment by fvazquez-caylent** [comment]
Rebased and merged changes in https://github.com/Datatamer/terraform-aws-rds-postgres/pull/17

**Pull request closed without merging**
