### PR TITLE
DEV-14729 & DEV-14295 - Updates minimum terraform and provider versions

### PR DESCRIPTION
**Pull request by souza-dan**
https://datatamr.atlassian.net/browse/DEV-14729
https://datatamr.atlassian.net/browse/DEV-14295

Ran plan for the example, but not apply:
```
var.ingress_sg_ids
  List of security group IDs to allow ingress from (i.e. Spark cluster SG IDs, Tamr VM SG ID)

  Enter a value: []

var.subnet_ids
  List of at least 2 subnets in different AZs for DB subnet group

  Enter a value: []

var.vpc_id
  VPC ID of network.

  Enter a value: []

Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.rds_postgres.aws_db_instance.rds_postgres will be created
  + resource "aws_db_instance" "rds_postgres" {
      + address                               = (known after apply)
      + allocated_storage                     = 20
      + apply_immediately                     = false
      + arn                                   = (known after apply)
      + auto_minor_version_upgrade            = true
      + availability_zone                     = (known after apply)
      + backup_retention_period               = 14
      + backup_window                         = "03:29-03:59"
      + ca_cert_identifier                    = (known after apply)
      + character_set_name                    = (known after apply)
      + copy_tags_to_snapshot                 = true
      + db_subnet_group_name                  = "example_subnet_group"
      + delete_automated_backups              = true
      + endpoint                              = (known after apply)
      + engine                                = "postgres"
      + engine_version                        = "12.3"
      + hosted_zone_id                        = (known after apply)
      + id                                    = (known after apply)
      + identifier                            = (known after apply)
      + identifier_prefix                     = "example-rds-pg-"
      + instance_class                        = "db.m4.large"
      + kms_key_id                            = (known after apply)
      + latest_restorable_time                = (known after apply)
      + license_model                         = (known after apply)
      + maintenance_window                    = "sun:04:32-sun:05:02"
      + max_allocated_storage                 = 1000
      + monitoring_interval                   = 0
      + monitoring_role_arn                   = (known after apply)
      + multi_az                              = true
      + name                                  = "example0"
      + option_group_name                     = (known after apply)
      + parameter_group_name                  = "example-rds-postgres-pg"
      + password                              = (sensitive value)
      + performance_insights_enabled          = false
      + performance_insights_kms_key_id       = (known after apply)
      + performance_insights_retention_period = (known after apply)
      + port                                  = 5432
      + publicly_accessible                   = false
      + replicas                              = (known after apply)
      + resource_id                           = (known after apply)
      + skip_final_snapshot                   = true
      + snapshot_identifier                   = (known after apply)
      + status                                = (known after apply)
      + storage_encrypted                     = true
      + storage_type                          = "gp2"
      + timezone                              = (known after apply)
      + username                              = "example-tamr-master"
      + vpc_security_group_ids                = (known after apply)
    }

  # module.rds_postgres.aws_db_parameter_group.rds_postgres_pg will be created
  + resource "aws_db_parameter_group" "rds_postgres_pg" {
      + arn         = (known after apply)
      + description = "TAMR RDS parameter group"
      + family      = "postgres12"
      + id          = (known after apply)
      + name        = "example-rds-postgres-pg"
      + name_prefix = (known after apply)
    }

  # module.rds_postgres.aws_db_subnet_group.rds_postgres_subnet_group will be created
  + resource "aws_db_subnet_group" "rds_postgres_subnet_group" {
      + arn         = (known after apply)
      + description = "Managed by Terraform"
      + id          = (known after apply)
      + name        = "example_subnet_group"
      + name_prefix = (known after apply)
    }

  # module.rds_postgres.module.rds_sg.aws_security_group.rds_postgres_sg will be created
  + resource "aws_security_group" "rds_postgres_sg" {
      + arn                    = (known after apply)
      + description            = "VPC Security group that will be attached to the RDS Postgres instance"
      + egress                 = (known after apply)
      + id                     = (known after apply)
      + ingress                = (known after apply)
      + name                   = "tamr_rds_sg"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + vpc_id                 = jsonencode([])
    }

Plan: 4 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

### CODE REVIEW

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Review by daniosim — APPROVED** [review]
👍

**Comment by tamr-teamcity** [comment]
This PR doesn't appear to be linked to a DevOps/SRE jira ticket

**Pull request merged**
